version: '3'
services:
  db:
    image: postgres:9.4
    volumes:
      - ./db/postgresql_setup.sql:/docker-entrypoint-initdb.d/postgresql_setup.sql
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
  rna:
    build: rna/
    ports:
      - "3001:3001"
    depends_on:
      - db
    network_mode: "host"
  sirene:
    build: sirene/
    ports:
      - "3002:3002"
    depends_on:
      - db
    network_mode: "host"
